"use client";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { AlertCircle, CheckCircle2, Clipboard, Download, Filter, Lightbulb, Plus, Printer, RotateCcw, Save, Search, UsersRound, WifiOff, X } from "lucide-react";
import { saveBudgetPlan } from "@/app/actions/budget";
import { Button, ButtonLink } from "@/components/ui/button";
import { Input, Select } from "@/components/ui/field";
import { trackBudgetEvent } from "@/lib/budget/analytics";
import { calculateBudget, findDuplicateImportedListing, formatMoney, getItemPlanningCost, parseMoneyToPence } from "@/lib/budget/calculations";
import { BUDGET_STORAGE_KEY, createEmptyBudgetPlan, restoreBudgetPlan, serializeBudgetPlan } from "@/lib/budget/persistence";
import type { BudgetCategory, BudgetItem, BudgetPlan, PlannerListing } from "@/lib/budget/types";
import { BudgetSummary, EmptyBudgetSummary } from "./budget-summary";
import { CategorySection, ExpenseRow } from "./category-section";
import { ExpenseDialog } from "./expense-dialog";

type SaveState = { kind: "idle" | "saving" | "saved" | "error"; message: string; at?: string };
type ItemFilter = "all" | "estimated" | "confirmed" | "booked" | "deposit" | "paid" | "missing" | "due";

export function BudgetPlanner({ listings, cloudPlan, userId, preselectedListing }: { listings: PlannerListing[]; cloudPlan: BudgetPlan | null; userId: string | null; preselectedListing: PlannerListing | null }) {
  const [plan, setPlan] = useState<BudgetPlan>(() => cloudPlan ?? createEmptyBudgetPlan(userId));
  const [hydrated, setHydrated] = useState(false); const [dialogOpen, setDialogOpen] = useState(false); const [dialogCategoryId, setDialogCategoryId] = useState<string | undefined>();
  const [editingItem, setEditingItem] = useState<BudgetItem | null>(null); const [view, setView] = useState<"categories" | "items">("categories");
  const [filter, setFilter] = useState<ItemFilter>("all"); const [categoryFilter, setCategoryFilter] = useState("all"); const [toast, setToast] = useState("");
  const [saveState, setSaveState] = useState<SaveState>({ kind: "idle", message: "Saved on this device" }); const [storageAvailable, setStorageAvailable] = useState(true); const [online, setOnline] = useState(true);
  const [undo, setUndo] = useState<{ item: BudgetItem; index: number } | null>(null); const preselectionHandled = useRef(false);
  const summary = useMemo(() => calculateBudget(plan), [plan]);
  const updatePlan = useCallback((updater: (current: BudgetPlan) => BudgetPlan) => setPlan((current) => ({ ...updater(current), updatedAt: new Date().toISOString() })), []);

  useEffect(() => {
    const initialise = window.setTimeout(() => {
      setOnline(navigator.onLine);
      try {
        const local = restoreBudgetPlan(window.localStorage.getItem(BUDGET_STORAGE_KEY));
        const localIsNewer = local && (!cloudPlan || new Date(local.updatedAt).getTime() > new Date(cloudPlan.updatedAt).getTime());
        if (localIsNewer) { setPlan({ ...local, userId }); setSaveState({ kind: "saved", message: cloudPlan ? "Restored newer changes from this device" : "Restored from this device", at: local.updatedAt }); trackBudgetEvent("planner_restored", { source: "local" }); }
        else if (cloudPlan) { setPlan({ ...cloudPlan, userId }); trackBudgetEvent("planner_restored", { source: "account" }); }
      } catch { setStorageAvailable(false); setSaveState({ kind: "error", message: "Automatic device saving is unavailable" }); }
      setHydrated(true);
    }, 0);
    const onOnline = () => setOnline(true), onOffline = () => setOnline(false);
    window.addEventListener("online", onOnline); window.addEventListener("offline", onOffline); trackBudgetEvent("budget_planner_opened");
    return () => { window.removeEventListener("online", onOnline); window.removeEventListener("offline", onOffline); window.clearTimeout(initialise); };
  }, [cloudPlan, userId]);

  useEffect(() => {
    if (!hydrated || !preselectedListing || preselectionHandled.current) return;
    preselectionHandled.current = true;
    const timer = window.setTimeout(() => {
      const existing = plan.items.find((item) => item.listingId === preselectedListing.id);
      if (existing) { setEditingItem(existing); setDialogOpen(true); setToast(`${preselectedListing.name} is already in your plan. You can edit it here.`); return; }
      const imported = listingToItem(preselectedListing, plan); updatePlan((current) => ({ ...current, selectedVenueId: preselectedListing.id, items: [...current.items, imported] }));
      trackBudgetEvent("venue_imported", { pricing_available: preselectedListing.priceFromPence != null });
      if (preselectedListing.priceFromPence == null) { setEditingItem(imported); setDialogOpen(true); setToast("Venue added. Add an estimate or confirmed quote to include it in your totals."); }
      else setToast(`${preselectedListing.name} was added using its listed starting price as an estimate.`);
    }, 0);
    return () => window.clearTimeout(timer);
  }, [hydrated, preselectedListing, plan, updatePlan]);

  useEffect(() => {
    if (!hydrated) return;
    const timer = window.setTimeout(async () => {
      setSaveState((current) => ({ ...current, kind: "saving", message: userId ? "Saving changes…" : "Saving on this device…" }));
      try { window.localStorage.setItem(BUDGET_STORAGE_KEY, serializeBudgetPlan(plan)); setStorageAvailable(true); }
      catch { setStorageAvailable(false); setSaveState({ kind: "error", message: "Could not save on this device" }); return; }
      if (userId && online) {
        const result = await saveBudgetPlan({ ...plan, userId });
        if (result.ok) { setSaveState({ kind: "saved", message: "Saved to your account", ...(result.savedAt ? { at: result.savedAt } : {}) }); trackBudgetEvent("planner_saved", { destination: "account" }); }
        else setSaveState({ kind: "error", message: result.message ?? "Cloud save failed. Your plan remains saved on this device." });
      } else { setSaveState({ kind: "saved", message: online ? "Saved on this device" : "Saved offline on this device", at: new Date().toISOString() }); trackBudgetEvent("planner_saved", { destination: "local" }); }
    }, 700);
    return () => window.clearTimeout(timer);
  }, [plan, hydrated, userId, online]);
  useEffect(() => { if (!toast) return; const timer = window.setTimeout(() => setToast(""), 6000); return () => window.clearTimeout(timer); }, [toast]);
  useEffect(() => { if (summary.health === "over") trackBudgetEvent("budget_exceeded"); }, [summary.health]);

  function openAdd(categoryId?: string) { setEditingItem(null); setDialogCategoryId(categoryId); setDialogOpen(true); }
  function saveItem(item: BudgetItem) {
    const duplicate = findDuplicateImportedListing(plan.items, item.listingId, item.id);
    if (duplicate) { setEditingItem(duplicate); setToast(`${duplicate.itemName} is already in this plan. No duplicate was added.`); return; }
    const existed = plan.items.some((existing) => existing.id === item.id);
    updatePlan((current) => ({ ...current, selectedVenueId: item.categoryId === "venue" && item.listingId ? item.listingId : current.selectedVenueId, items: existed ? current.items.map((existing) => existing.id === item.id ? item : existing) : [...current.items, item] }));
    if (!existed) trackBudgetEvent(item.source === "website" ? "website_listing_added" : "expense_added_manually", { category: item.categoryId });
    if (item.importedPriceType === "unavailable" && getItemPlanningCost(item).amountPence != null) trackBudgetEvent("missing_price_completed");
    setDialogOpen(false); setEditingItem(null); setToast(existed ? "Expense updated." : "Expense added to your plan.");
  }
  function deleteItem(item: BudgetItem) { if (!window.confirm(`Delete “${item.itemName}” from your budget?`)) return; const index = plan.items.findIndex((existing) => existing.id === item.id); updatePlan((current) => ({ ...current, items: current.items.filter((existing) => existing.id !== item.id), selectedVenueId: current.selectedVenueId === item.listingId ? null : current.selectedVenueId })); setUndo({ item, index }); setToast("Expense deleted. You can undo this change."); }
  function undoDelete() { if (!undo) return; updatePlan((current) => { const items = [...current.items]; items.splice(undo.index, 0, undo.item); return { ...current, items }; }); setUndo(null); setToast("Expense restored."); }
  function duplicateItem(item: BudgetItem) { const now = new Date().toISOString(); const copy = { ...item, id: crypto.randomUUID(), listingId: null, listingUrl: null, source: "manual" as const, itemName: `${item.itemName} (copy)`, createdAt: now, updatedAt: now, sortOrder: plan.items.length }; updatePlan((current) => ({ ...current, items: [...current.items, copy] })); setToast("Expense duplicated."); }
  function moveItem(item: BudgetItem, direction: -1 | 1) { updatePlan((current) => { const inCategory = current.items.filter((candidate) => candidate.categoryId === item.categoryId).sort((a, b) => a.sortOrder - b.sortOrder); const index = inCategory.findIndex((candidate) => candidate.id === item.id); const swap = inCategory[index + direction]; if (!swap) return current; return { ...current, items: current.items.map((candidate) => candidate.id === item.id ? { ...candidate, sortOrder: swap.sortOrder } : candidate.id === swap.id ? { ...candidate, sortOrder: item.sortOrder } : candidate) }; }); }
  function addCategory() { const name = window.prompt("Name your custom category"); if (!name?.trim()) return; const category: BudgetCategory = { id: `custom-${crypto.randomUUID()}`, name: name.trim().slice(0, 100), isCustom: true, targetPence: null, collapsed: false }; updatePlan((current) => ({ ...current, categories: [...current.categories, category] })); }
  function renameCategory(category: BudgetCategory) { const name = window.prompt("Rename category", category.name); if (!name?.trim()) return; updatePlan((current) => ({ ...current, categories: current.categories.map((candidate) => candidate.id === category.id ? { ...candidate, name: name.trim().slice(0, 100) } : candidate) })); }
  function deleteCategory(category: BudgetCategory) { if (plan.items.some((item) => item.categoryId === category.id)) { setToast("Move or delete this category’s expenses first."); return; } if (!window.confirm(`Delete the empty “${category.name}” category?`)) return; updatePlan((current) => ({ ...current, categories: current.categories.filter((candidate) => candidate.id !== category.id) })); }
  function resetPlan() { if (!window.confirm("Reset this budget planner? All items and wedding details on this device will be removed.")) return; setPlan(createEmptyBudgetPlan(userId)); setToast("Planner reset."); }

  const filteredItems = useMemo(() => plan.items.filter((item) => {
    if (categoryFilter !== "all" && item.categoryId !== categoryFilter) return false; const cost = getItemPlanningCost(item);
    if (filter === "estimated") return cost.kind === "estimated" || cost.kind === "per_person"; if (filter === "confirmed") return cost.kind === "confirmed";
    if (filter === "booked") return item.bookingStatus === "booked"; if (filter === "deposit") return item.depositPaidPence > 0 && item.paymentStatus !== "paid";
    if (filter === "paid") return item.paymentStatus === "paid"; if (filter === "missing") return cost.kind === "missing"; if (filter === "due") return isDueSoon(item.dueDate); return true;
  }), [plan.items, filter, categoryFilter]);

  function exportCsv() {
    const rows = [["Category", "Item", "Supplier", "Source", "Status", "Estimated", "Confirmed", "Paid", "Outstanding", "Due date", "Notes"]];
    for (const item of plan.items) { const category = plan.categories.find((candidate) => candidate.id === item.categoryId)?.name ?? item.categoryId; const cost = getItemPlanningCost(item).amountPence; const paid = Math.max(item.totalPaidPence, item.depositPaidPence); rows.push([category, item.itemName, item.supplierName ?? "", item.source, item.costStatus, item.estimatedCostPence == null ? "" : String(item.estimatedCostPence / 100), item.confirmedCostPence == null ? "" : String(item.confirmedCostPence / 100), String(paid / 100), cost == null ? "" : String(Math.max(cost - paid, 0) / 100), item.dueDate ?? "", item.notes ?? ""]); }
    const csv = rows.map((row) => row.map((value) => `"${value.replaceAll('"', '""')}"`).join(",")).join("\r\n"); const url = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "everaft-wedding-budget.csv"; anchor.click(); URL.revokeObjectURL(url); trackBudgetEvent("export_used", { format: "csv" });
  }
  function printPlan() { setPlan((current) => ({ ...current, categories: current.categories.map((category) => ({ ...category, collapsed: false })) })); window.setTimeout(() => window.print(), 50); trackBudgetEvent("export_used", { format: "print" }); }
  async function copySummary() { const text = `EverAft wedding budget\nTotal budget: ${formatMoney(plan.totalBudgetPence, plan.currency)}\nAllocated: ${formatMoney(summary.allocatedPence, plan.currency)}\nBudget remaining: ${formatMoney(summary.remainingPence, plan.currency)}\nPaid: ${formatMoney(summary.totalPaidPence, plan.currency)}\nStill to pay suppliers: ${formatMoney(summary.outstandingPence, plan.currency)}`; try { await navigator.clipboard.writeText(text); setToast("Budget summary copied."); trackBudgetEvent("export_used", { format: "clipboard" }); } catch { setToast("Copy failed. Your browser may block clipboard access."); } }

  return <div className="relative"><div className="mx-auto max-w-7xl px-4 pb-24 sm:px-6 lg:px-8"><div className="flex flex-col gap-3 pb-6 pt-8 sm:flex-row sm:items-end sm:justify-between sm:pt-10"><div><h1 className="font-display text-4xl font-semibold leading-tight text-[var(--brand)] sm:text-5xl">Wedding Budget Planner</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[var(--muted)] sm:text-base">Set your total budget, add venues and suppliers, and see exactly how much you have left as you plan your day.</p><p className="mt-2 text-xs text-[#7b746a]">Listed prices are planning estimates unless a supplier has explicitly confirmed your quote.</p></div><SaveIndicator state={saveState} online={online} /></div>
    <div className="grid gap-5">{plan.totalBudgetPence > 0 ? <BudgetSummary plan={plan} summary={summary} /> : <EmptyBudgetSummary />}<BudgetSetup plan={plan} summary={summary} updatePlan={updatePlan} /></div>
    <div className="mt-6 grid gap-6 lg:grid-cols-[minmax(0,1fr)_330px]"><main className="min-w-0"><div className="mb-4 flex flex-col gap-3 xl:flex-row xl:items-center xl:justify-between print:hidden"><div className="inline-flex self-start rounded-full bg-[#eee8dd] p-1"><button className={`focus-ring inline-flex min-h-10 items-center gap-2 rounded-full px-4 text-sm font-semibold ${view === "categories" ? "bg-[var(--brand)] text-white" : "text-[#625f57]"}`} onClick={() => setView("categories")} aria-pressed={view === "categories"}>Category view</button><button className={`focus-ring inline-flex min-h-10 items-center gap-2 rounded-full px-4 text-sm font-semibold ${view === "items" ? "bg-[var(--brand)] text-white" : "text-[#625f57]"}`} onClick={() => setView("items")} aria-pressed={view === "items"}>All items</button></div><div className="flex flex-wrap gap-2"><label className="relative"><span className="sr-only">Filter by category</span><Filter className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-[#8a806f]" size={15} /><Select className="h-10 w-auto pl-9 pr-9" value={categoryFilter} onChange={(e) => setCategoryFilter(e.target.value)}><option value="all">All categories</option>{plan.categories.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</Select></label><label><span className="sr-only">Filter by status</span><Select className="h-10 w-auto" value={filter} onChange={(e) => setFilter(e.target.value as ItemFilter)}><option value="all">All statuses</option><option value="estimated">Estimated</option><option value="confirmed">Confirmed</option><option value="booked">Booked</option><option value="deposit">Deposit paid</option><option value="paid">Fully paid</option><option value="missing">Missing price</option><option value="due">Payment due soon</option></Select></label></div></div>
      {view === "categories" ? <div className="grid gap-3">{plan.categories.filter((c) => categoryFilter === "all" || c.id === categoryFilter).map((category) => { const items = filteredItems.filter((i) => i.categoryId === category.id).sort((a, b) => a.sortOrder - b.sortOrder); return <CategorySection key={category.id} category={category} items={items} currency={plan.currency} totalPence={summary.categoryTotals.get(category.id) ?? 0} onToggle={() => updatePlan((current) => ({ ...current, categories: current.categories.map((candidate) => candidate.id === category.id ? { ...candidate, collapsed: !candidate.collapsed } : candidate) }))} onAdd={() => openAdd(category.id)} onEdit={(item) => { setEditingItem(item); setDialogOpen(true); }} onDuplicate={duplicateItem} onDelete={deleteItem} onMove={moveItem} onRename={() => renameCategory(category)} onDeleteCategory={() => deleteCategory(category)} onTargetChange={(value) => updatePlan((current) => ({ ...current, categories: current.categories.map((candidate) => candidate.id === category.id ? { ...candidate, targetPence: parseMoneyToPence(value) } : candidate) }))} />; })}<button type="button" onClick={addCategory} className="focus-ring min-h-14 rounded-3xl border border-dashed border-[#cbbdac] bg-white/40 text-sm font-semibold text-[#9c542d] transition hover:bg-white"><Plus className="mr-2 inline" size={17} />Add a custom category</button></div> : <AllItems items={filteredItems} plan={plan} onEdit={(item) => { setEditingItem(item); setDialogOpen(true); }} onDuplicate={duplicateItem} onDelete={deleteItem} onMove={moveItem} onAdd={() => openAdd()} />}
    </main><aside className="grid content-start gap-4 print:hidden lg:sticky lg:top-24 lg:self-start"><Button className="w-full bg-[#a94f2b] py-3 text-base hover:bg-[#8f4224]" onClick={() => openAdd()}><Plus size={19} /> Add expense</Button><Insights plan={plan} summary={summary} /><PaymentOverview plan={plan} summary={summary} /><section className="rounded-3xl border border-[var(--line)] bg-white p-5"><h2 className="font-display text-2xl font-semibold">Export your plan</h2><div className="mt-4 grid gap-2"><button onClick={exportCsv} className="focus-ring flex min-h-11 items-center gap-3 rounded-xl px-3 text-left text-sm font-semibold hover:bg-[#f7f1e8]"><Download size={17} /> Download CSV</button><button onClick={printPlan} className="focus-ring flex min-h-11 items-center gap-3 rounded-xl px-3 text-left text-sm font-semibold hover:bg-[#f7f1e8]"><Printer size={17} /> Print budget</button><button onClick={copySummary} className="focus-ring flex min-h-11 items-center gap-3 rounded-xl px-3 text-left text-sm font-semibold hover:bg-[#f7f1e8]"><Clipboard size={17} /> Copy summary</button></div></section>{!userId ? <section className="rounded-3xl border border-[#d7c49d] bg-[#fff9ef] p-5"><h2 className="font-display text-2xl font-semibold">Keep it safe across devices</h2><p className="mt-2 text-sm leading-6 text-[#6a5b42]">Your plan is saved in this browser. Create an account to sync it securely when account saving is enabled.</p><ButtonLink href="/signup?redirectTo=/wedding-budget-planner" className="mt-4 w-full" onClick={() => trackBudgetEvent("account_creation_prompt_clicked")}>Create an account</ButtonLink></section> : null}<button type="button" onClick={resetPlan} className="focus-ring inline-flex min-h-11 items-center justify-center gap-2 rounded-full text-sm font-semibold text-[#8b3029] hover:bg-[#fff1ef]"><RotateCcw size={16} /> Reset planner</button></aside></div></div>
    <div className="fixed inset-x-0 bottom-0 z-30 flex items-center justify-between border-t border-white/15 bg-[var(--brand)] px-4 py-3 text-white shadow-[0_-12px_35px_rgba(21,32,23,.2)] lg:hidden print:hidden"><div><p className="text-[11px] text-white/65">{summary.remainingPence < 0 ? "Over budget" : "Budget remaining"}</p><p className="font-display text-2xl font-semibold">{formatMoney(Math.abs(summary.remainingPence), plan.currency)}</p></div><Button className="bg-white text-[var(--brand)] hover:bg-[#f4efe7]" style={{ color: "var(--brand)" }} onClick={() => openAdd()}><Plus size={17} /> Add expense</Button></div>
    {toast ? <div className="fixed bottom-24 left-1/2 z-[60] flex max-w-[calc(100%-2rem)] -translate-x-1/2 items-center gap-3 rounded-full bg-[#152017] px-5 py-3 text-sm font-medium text-white shadow-xl print:hidden" role="status"><CheckCircle2 size={17} className="shrink-0 text-[#bad4b6]" /><span>{toast}</span>{undo ? <button className="focus-ring rounded-full px-2 py-1 font-bold text-[#f1c19f]" onClick={undoDelete}>Undo</button> : null}<button className="focus-ring grid size-7 place-items-center rounded-full hover:bg-white/10" onClick={() => { setToast(""); setUndo(null); }} aria-label="Dismiss"><X size={15} /></button></div> : null}
    {!storageAvailable ? <div className="fixed left-4 top-24 z-40 max-w-sm rounded-2xl bg-[#fff1ef] p-4 text-sm text-[#8b3029] shadow-lg" role="alert"><AlertCircle className="mr-2 inline" size={16} />Automatic saving is unavailable. Keep this tab open or export your plan.</div> : null}
    {dialogOpen ? <ExpenseDialog open plan={plan} listings={listings} initialCategoryId={dialogCategoryId} item={editingItem} onClose={() => { setDialogOpen(false); setEditingItem(null); }} onSave={saveItem} /> : null}
  </div>;
}

function BudgetSetup({ plan, summary, updatePlan }: { plan: BudgetPlan; summary: ReturnType<typeof calculateBudget>; updatePlan: (updater: (current: BudgetPlan) => BudgetPlan) => void }) {
  return <section className="rounded-3xl border border-[var(--line)] bg-white p-5 sm:p-6 print:break-inside-avoid"><div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-5"><Label text="Total wedding budget"><MoneyField valuePence={plan.totalBudgetPence} onChange={(value) => { updatePlan((current) => ({ ...current, totalBudgetPence: value ?? 0 })); if ((value ?? 0) > 0) trackBudgetEvent("budget_entered"); }} required /></Label><Label text="Wedding date (optional)"><Input type="date" value={plan.weddingDate ?? ""} onChange={(e) => updatePlan((current) => ({ ...current, weddingDate: e.target.value || null }))} /></Label><Label text="Guest count (optional)"><Input inputMode="numeric" type="number" min="1" max="10000" value={plan.guestCount ?? ""} onChange={(e) => updatePlan((current) => ({ ...current, guestCount: e.target.value ? Number(e.target.value) : null }))} placeholder="e.g. 80" /></Label><Label text="Location (optional)"><Input value={plan.location ?? ""} onChange={(e) => updatePlan((current) => ({ ...current, location: e.target.value || null }))} placeholder="Town, region or venue" maxLength={160} /></Label><Label text="Currency"><Select value={plan.currency} onChange={(e) => updatePlan((current) => ({ ...current, currency: e.target.value as BudgetPlan["currency"] }))}><option value="GBP">GBP (£)</option><option value="EUR">EUR (€)</option><option value="USD">USD ($)</option></Select></Label></div><div className="mt-5 flex flex-col gap-4 border-t border-[var(--line)] pt-5 sm:flex-row sm:items-end"><Label text="Contingency fund"><Select value={plan.contingencyType} onChange={(e) => updatePlan((current) => ({ ...current, contingencyType: e.target.value as BudgetPlan["contingencyType"], contingencyValue: e.target.value === "percentage" ? 5 : 0 }))}><option value="none">No contingency yet</option><option value="percentage">Percentage of budget</option><option value="fixed">Fixed amount</option></Select></Label>{plan.contingencyType !== "none" ? <Label text={plan.contingencyType === "percentage" ? "Percentage (%)" : "Amount (£)"}><Input className="sm:w-40" inputMode="decimal" value={plan.contingencyType === "percentage" ? plan.contingencyValue : plan.contingencyValue / 100} onChange={(e) => updatePlan((current) => ({ ...current, contingencyValue: current.contingencyType === "percentage" ? Math.min(Math.max(Number(e.target.value) || 0, 0), 100) : parseMoneyToPence(e.target.value) ?? 0 }))} /></Label> : null}<div className="text-sm text-[var(--muted)] sm:ml-auto sm:text-right"><p><strong className="text-[var(--foreground)]">{formatMoney(summary.contingencyPence, plan.currency)}</strong> reserved</p><p className="mt-1"><strong className="text-[var(--foreground)]">{formatMoney(summary.spendableBudgetPence, plan.currency)}</strong> spendable budget</p></div></div></section>;
}
function MoneyField({ valuePence, onChange, required = false }: { valuePence: number; onChange: (value: number | null) => void; required?: boolean }) { return <span className="relative"><span className="pointer-events-none absolute left-4 top-1/2 -translate-y-1/2 font-semibold text-[#756d62]">£</span><Input className="pl-8" inputMode="decimal" value={valuePence ? valuePence / 100 : ""} onChange={(e) => onChange(parseMoneyToPence(e.target.value))} placeholder="0.00" required={required} /></span>; }
function Label({ text, children }: { text: string; children: React.ReactNode }) { return <label className="grid min-w-0 gap-2 text-sm font-medium text-[#4a443c]"><span>{text}</span>{children}</label>; }
function SaveIndicator({ state, online }: { state: SaveState; online: boolean }) { return <div className={`flex items-center gap-2 self-start rounded-full px-3 py-2 text-xs font-semibold ${state.kind === "error" ? "bg-[#fff1ef] text-[#8b3029]" : "bg-white text-[#52604f] ring-1 ring-[var(--line)]"}`} aria-live="polite">{!online ? <WifiOff size={14} /> : state.kind === "saving" ? <Save size={14} className="animate-pulse" /> : state.kind === "error" ? <AlertCircle size={14} /> : <CheckCircle2 size={14} />}<span>{state.message}{state.at ? ` · ${new Date(state.at).toLocaleTimeString("en-GB", { hour: "2-digit", minute: "2-digit" })}` : ""}</span></div>; }
function Insights({ plan, summary }: { plan: BudgetPlan; summary: ReturnType<typeof calculateBudget> }) { const categoryNames = new Map(plan.categories.map((c) => [c.id, c.name])); const dueCount = plan.items.filter((item) => isDueSoon(item.dueDate)).length; return <section className="rounded-3xl border border-[var(--line)] bg-white p-5"><h2 className="flex items-center gap-3 font-display text-2xl font-semibold"><span className="grid size-9 place-items-center rounded-full bg-[#f4efe7] text-[#8b6d3c]"><Lightbulb size={18} /></span>Planning insights</h2><div className="mt-4 grid gap-3 text-sm"><Insight icon={<CheckCircle2 size={16} />} title={summary.health === "over" ? `You’re ${formatMoney(Math.abs(summary.remainingPence), plan.currency)} over budget` : summary.health === "close" ? "You’re approaching your limit" : "Your plan is on track"} text={summary.health === "over" ? `Your largest categories are ${summary.largestCategories.map((entry) => categoryNames.get(entry.categoryId)).filter(Boolean).join(", ") || "still being planned"}.` : `${summary.percentUsed}% of your spendable budget is allocated.`} warning={summary.health === "over"} />{summary.missingPriceCount > 0 ? <Insight icon={<AlertCircle size={16} />} title={`${summary.missingPriceCount} missing ${summary.missingPriceCount === 1 ? "price" : "prices"}`} text="Add an estimate so the plan gives you the full picture." warning /> : null}{dueCount > 0 ? <Insight icon={<Save size={16} />} title={`${dueCount} payment ${dueCount === 1 ? "is" : "are"} due soon`} text="Due within the next 30 days." /> : null}{plan.guestCount && summary.allocatedPence > 0 ? <Insight icon={<UsersRound size={16} />} title={`${formatMoney(Math.round(summary.allocatedPence / plan.guestCount), plan.currency)} per guest`} text={`Based on ${plan.guestCount} guests and your current allocation.`} /> : null}{plan.contingencyType === "none" ? <Insight icon={<Lightbulb size={16} />} title="Consider a contingency" text="Many couples reserve around 5%, but it is entirely optional." /> : null}</div></section>; }
function Insight({ icon, title, text, warning = false }: { icon: React.ReactNode; title: string; text: string; warning?: boolean }) { return <div className="flex gap-3 border-t border-[var(--line)] pt-3 first:border-0 first:pt-0"><span className={`mt-0.5 grid size-8 shrink-0 place-items-center rounded-full ${warning ? "bg-[#fff1ef] text-[#a44831]" : "bg-[#f4efe7] text-[#66725f]"}`}>{icon}</span><div><p className="font-semibold">{title}</p><p className="mt-1 text-xs leading-5 text-[var(--muted)]">{text}</p></div></div>; }
function PaymentOverview({ plan, summary }: { plan: BudgetPlan; summary: ReturnType<typeof calculateBudget> }) { return <section className="rounded-3xl border border-[var(--line)] bg-white p-5"><h2 className="font-display text-2xl font-semibold">Payment overview</h2><dl className="mt-4 grid gap-3 text-sm"><Row label="Confirmed costs" value={formatMoney(summary.confirmedPence, plan.currency)} /><Row label="Estimated costs" value={formatMoney(summary.estimatedPence, plan.currency)} /><Row label="Already paid" value={formatMoney(summary.totalPaidPence, plan.currency)} /><Row label="Still to pay suppliers" value={formatMoney(summary.outstandingPence, plan.currency)} strong /><Row label="Budget remaining" value={formatMoney(summary.remainingPence, plan.currency)} strong /></dl><p className="mt-4 border-t border-[var(--line)] pt-4 text-xs leading-5 text-[var(--muted)]">Budget remaining is what you can still allocate. Still to pay is the unpaid balance on expenses already in your plan.</p></section>; }
function Row({ label, value, strong = false }: { label: string; value: string; strong?: boolean }) { return <div className={`flex items-center justify-between gap-3 ${strong ? "font-semibold" : ""}`}><dt>{label}</dt><dd>{value}</dd></div>; }
function AllItems({ items, plan, onEdit, onDuplicate, onDelete, onMove, onAdd }: { items: BudgetItem[]; plan: BudgetPlan; onEdit: (i: BudgetItem) => void; onDuplicate: (i: BudgetItem) => void; onDelete: (i: BudgetItem) => void; onMove: (i: BudgetItem, d: -1 | 1) => void; onAdd: () => void }) { return <section className="rounded-3xl border border-[var(--line)] bg-white p-4 sm:p-5"><div className="flex items-center justify-between"><div><h2 className="font-display text-2xl font-semibold">All expenses</h2><p className="mt-1 text-xs text-[var(--muted)]">{items.length} matching {items.length === 1 ? "item" : "items"}</p></div><Button onClick={onAdd}><Plus size={16} /> Add</Button></div>{items.length ? <div className="mt-4 grid gap-3">{items.map((item, index) => <div key={item.id}><p className="mb-1 px-2 text-[11px] font-semibold uppercase tracking-[0.1em] text-[#8a806f]">{plan.categories.find((c) => c.id === item.categoryId)?.name}</p><ExpenseRow item={item} currency={plan.currency} onEdit={() => onEdit(item)} onDuplicate={() => onDuplicate(item)} onDelete={() => onDelete(item)} onMoveUp={() => onMove(item, -1)} onMoveDown={() => onMove(item, 1)} first={index === 0} last={index === items.length - 1} /></div>)}</div> : <div className="mt-4 rounded-2xl border border-dashed border-[var(--line)] p-8 text-center"><Search className="mx-auto text-[#9d7b45]" /><h3 className="mt-3 font-display text-2xl font-semibold">No matching expenses</h3><p className="mt-1 text-sm text-[var(--muted)]">Change the filters or add a new item.</p></div>}</section>; }
function listingToItem(listing: PlannerListing, plan: BudgetPlan): BudgetItem { const now = new Date().toISOString(); return { id: crypto.randomUUID(), categoryId: "venue", listingId: listing.id, listingType: listing.type, listingUrl: listing.listingUrl, imageUrl: listing.imageUrl, source: "website", itemName: listing.name, supplierName: listing.name, supplierType: listing.type, description: null, estimatedCostPence: listing.priceFromPence, confirmedCostPence: null, importedPricePence: listing.priceFromPence, importedPriceToPence: listing.priceToPence, importedPriceType: listing.pricingStatus, costPerPersonPence: null, guestCount: plan.guestCount, depositPaidPence: 0, totalPaidPence: 0, costStatus: "estimated", paymentStatus: "not_started", bookingStatus: "shortlisted", dueDate: null, websiteUrl: listing.listingUrl, notes: null, createdAt: now, updatedAt: now, sortOrder: plan.items.length }; }
function isDueSoon(date: string | null) { if (!date) return false; const due = new Date(`${date}T23:59:59`).getTime(), now = Date.now(); return due >= now && due <= now + 30 * 24 * 60 * 60 * 1000; }
