import { AlertTriangle, CheckCircle2, Gauge, TrendingUp } from "lucide-react";
import { calculateBudget, formatMoney } from "@/lib/budget/calculations";
import type { BudgetPlan } from "@/lib/budget/types";
type Summary = ReturnType<typeof calculateBudget>;

export function BudgetSummary({ plan, summary }: { plan: BudgetPlan; summary: Summary }) {
  const status = summary.health === "over" ? { label: "Budget exceeded", icon: <AlertTriangle size={16} />, colour: "text-[#ffd6cb]" } : summary.health === "close" ? { label: "Approaching your limit", icon: <TrendingUp size={16} />, colour: "text-[#ffe0a6]" } : { label: "Healthy budget remaining", icon: <CheckCircle2 size={16} />, colour: "text-[#d6ead4]" };
  return <section className="overflow-hidden rounded-[1.75rem] bg-[var(--brand)] text-white soft-shadow" aria-labelledby="budget-summary-title"><div className="grid gap-6 p-5 sm:p-7 lg:grid-cols-[1.1fr_2fr_auto] lg:items-center"><div><p id="budget-summary-title" className={`flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.14em] ${status.colour}`}>{status.icon}{status.label}</p><p className="mt-2 font-display text-4xl font-semibold leading-none sm:text-5xl">{formatMoney(Math.abs(summary.remainingPence), plan.currency)}</p><p className="mt-2 text-sm text-white/70">{summary.remainingPence < 0 ? "over your spendable budget" : "remaining to allocate"}</p></div><div className="grid grid-cols-2 gap-x-5 gap-y-4 border-y border-white/15 py-5 sm:grid-cols-4 lg:border-x lg:border-y-0 lg:px-7 lg:py-1"><Metric label="Total budget" value={formatMoney(plan.totalBudgetPence, plan.currency)} /><Metric label="Allocated" value={formatMoney(summary.allocatedPence, plan.currency)} /><Metric label="Already paid" value={formatMoney(summary.totalPaidPence, plan.currency)} /><Metric label="Still to pay" value={formatMoney(summary.outstandingPence, plan.currency)} /></div><div className="flex items-center gap-4 lg:block lg:text-center"><span className="relative grid size-[4.5rem] shrink-0 place-items-center rounded-full" style={{ background: `conic-gradient(#d17c52 ${Math.min(summary.percentUsed, 100) * 3.6}deg, rgba(255,255,255,.18) 0)` }} aria-hidden="true"><span className="grid size-[3.45rem] place-items-center rounded-full bg-[var(--brand)] text-sm font-semibold">{summary.percentUsed}%</span></span><div className="lg:mt-2"><p className="text-sm font-semibold">Budget planned</p><p className="mt-1 text-xs text-white/60">{summary.activeItemCount} {summary.activeItemCount === 1 ? "item" : "items"}</p></div><span className="sr-only">{summary.percentUsed}% of the spendable budget has been allocated.</span></div></div><div className="h-1.5 bg-white/12" role="progressbar" aria-label="Budget allocated" aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.min(summary.percentUsed, 100)}><div className="h-full bg-[#d17c52] transition-[width] duration-300" style={{ width: `${Math.min(summary.percentUsed, 100)}%` }} /></div></section>;
}
function Metric({ label, value }: { label: string; value: string }) { return <div><p className="text-lg font-semibold sm:text-xl">{value}</p><p className="mt-1 text-xs text-white/60">{label}</p></div>; }
export function EmptyBudgetSummary() { return <section className="rounded-[1.75rem] border border-[var(--line)] bg-white p-6 sm:p-8"><div className="flex items-start gap-4"><span className="grid size-11 shrink-0 place-items-center rounded-full bg-[#f4efe7] text-[#8b6d3c]"><Gauge size={20} /></span><div><h2 className="font-display text-2xl font-semibold">Start with your total budget</h2><p className="mt-1 max-w-xl text-sm leading-6 text-[var(--muted)]">Add the amount you are comfortable spending. Your remaining budget, category totals and payment figures will update instantly.</p></div></div></section>; }

