"use client";
import Link from "next/link";
import { AlertCircle, CheckCircle2, ChevronDown, ChevronUp, Copy, Edit3, ExternalLink, GripVertical, Plus, Trash2 } from "lucide-react";
import { formatMoney, getItemPlanningCost } from "@/lib/budget/calculations";
import type { BudgetCategory, BudgetItem, CurrencyCode } from "@/lib/budget/types";

type Props = { category: BudgetCategory; items: BudgetItem[]; currency: CurrencyCode; totalPence: number; onToggle: () => void; onAdd: () => void; onEdit: (item: BudgetItem) => void; onDuplicate: (item: BudgetItem) => void; onDelete: (item: BudgetItem) => void; onMove: (item: BudgetItem, direction: -1 | 1) => void; onRename: () => void; onDeleteCategory: () => void; onTargetChange: (value: string) => void };
export function CategorySection({ category, items, currency, totalPence, onToggle, onAdd, onEdit, onDuplicate, onDelete, onMove, onRename, onDeleteCategory, onTargetChange }: Props) {
  const targetExceeded = category.targetPence != null && totalPence > category.targetPence;
  return <section className="overflow-hidden rounded-3xl border border-[var(--line)] bg-white print:break-inside-avoid"><div className="flex items-center gap-3 px-4 py-4 sm:px-5"><button type="button" className="focus-ring flex min-w-0 flex-1 items-center gap-3 rounded-xl text-left" onClick={onToggle} aria-expanded={!category.collapsed}><span className="grid size-10 shrink-0 place-items-center rounded-full bg-[#f4efe7] font-display text-lg font-semibold text-[#77583c]">{category.name.slice(0, 1)}</span><span className="min-w-0"><span className="block truncate font-display text-xl font-semibold sm:text-2xl">{category.name}</span><span className={`mt-0.5 block text-xs ${targetExceeded ? "font-semibold text-[#a44831]" : "text-[var(--muted)]"}`}>{items.length} {items.length === 1 ? "item" : "items"}{category.targetPence != null ? ` · ${formatMoney(totalPence, currency)} of ${formatMoney(category.targetPence, currency)} target` : ""}{targetExceeded ? " · over target" : ""}</span></span></button><p className="hidden text-right sm:block"><span className="block font-semibold">{formatMoney(totalPence, currency)}</span><span className="text-xs text-[var(--muted)]">allocated</span></p><button type="button" className="focus-ring grid size-10 place-items-center rounded-full hover:bg-[#f7f1e8]" onClick={onToggle} aria-label={`${category.collapsed ? "Expand" : "Collapse"} ${category.name}`}>{category.collapsed ? <ChevronDown size={18} /> : <ChevronUp size={18} />}</button></div>
    {!category.collapsed ? <div className="border-t border-[var(--line)] px-4 pb-4 sm:px-5"><div className="flex flex-wrap items-center justify-between gap-3 py-3 text-xs text-[var(--muted)]"><label className="flex items-center gap-2">Category target (£)<input className="focus-ring h-9 w-28 rounded-full border border-[var(--line)] px-3" inputMode="decimal" value={category.targetPence == null ? "" : category.targetPence / 100} onChange={(e) => onTargetChange(e.target.value)} placeholder="Optional" /></label>{category.suggestedPercentage ? <span>Planning suggestion: around {category.suggestedPercentage}%</span> : null}{category.isCustom ? <span className="flex gap-1"><button className="focus-ring rounded-full px-3 py-2 font-semibold hover:bg-[#f7f1e8]" type="button" onClick={onRename}>Rename</button><button className="focus-ring rounded-full px-3 py-2 font-semibold text-[#8b3029] hover:bg-[#fff1ef]" type="button" onClick={onDeleteCategory} disabled={items.length > 0}>Delete category</button></span> : null}</div>
      {items.length ? <div className="grid gap-3">{items.map((item, index) => <ExpenseRow key={item.id} item={item} currency={currency} onEdit={() => onEdit(item)} onDuplicate={() => onDuplicate(item)} onDelete={() => onDelete(item)} onMoveUp={() => onMove(item, -1)} onMoveDown={() => onMove(item, 1)} first={index === 0} last={index === items.length - 1} />)}</div> : <div className="rounded-2xl border border-dashed border-[var(--line)] bg-[#fdfbf7] p-5 text-center"><p className="text-sm font-medium">Nothing planned here yet</p><p className="mt-1 text-xs text-[var(--muted)]">Add a quote, supplier, fee or estimate when you are ready.</p></div>}
      <button type="button" onClick={onAdd} className="focus-ring mt-3 inline-flex min-h-10 items-center gap-2 rounded-full px-3 text-sm font-semibold text-[#9c542d] transition hover:bg-[#fff4ed]"><Plus size={16} /> Add expense to {category.name}</button></div> : null}</section>;
}

export function ExpenseRow({ item, currency, onEdit, onDuplicate, onDelete, onMoveUp, onMoveDown, first, last }: { item: BudgetItem; currency: CurrencyCode; onEdit: () => void; onDuplicate: () => void; onDelete: () => void; onMoveUp: () => void; onMoveDown: () => void; first: boolean; last: boolean }) {
  const cost = getItemPlanningCost(item); const paid = Math.max(item.totalPaidPence, item.depositPaidPence); const outstanding = cost.amountPence == null ? null : Math.max(cost.amountPence - paid, 0);
  return <article className="group rounded-2xl border border-[#e8e1d7] bg-[#fffdf9] p-4 transition hover:border-[#d4c5b5]"><div className="grid gap-4 md:grid-cols-[minmax(0,1.7fr)_repeat(3,minmax(90px,.55fr))_auto] md:items-center"><div className="min-w-0"><div className="flex items-center gap-2"><GripVertical size={15} className="hidden shrink-0 text-[#b7afa4] md:block" aria-hidden="true" /><h3 className="truncate text-sm font-semibold">{item.itemName}</h3></div><p className="mt-1 truncate text-xs text-[var(--muted)]">{item.supplierName || (item.source === "website" ? "Imported from EverAft" : "Manual expense")}</p>{item.listingUrl ? <Link href={item.listingUrl} target="_blank" className="focus-ring mt-1 inline-flex items-center gap-1 rounded text-xs font-medium text-[#5c6b52] hover:underline">View listing <ExternalLink size={12} /></Link> : null}</div><SmallMetric label={cost.kind === "confirmed" ? "Confirmed" : cost.kind === "cancelled" ? "Cancelled" : "Planning cost"} value={cost.amountPence == null ? "Price missing" : formatMoney(cost.amountPence, currency)} warning={cost.amountPence == null} /><SmallMetric label="Paid" value={formatMoney(paid, currency)} /><SmallMetric label="Still to pay" value={outstanding == null ? "—" : formatMoney(outstanding, currency)} /><div className="flex items-center justify-end gap-1 print:hidden"><button type="button" className="focus-ring grid size-9 place-items-center rounded-full hover:bg-white disabled:opacity-30" onClick={onMoveUp} disabled={first} aria-label={`Move ${item.itemName} up`}><ChevronUp size={16} /></button><button type="button" className="focus-ring grid size-9 place-items-center rounded-full hover:bg-white disabled:opacity-30" onClick={onMoveDown} disabled={last} aria-label={`Move ${item.itemName} down`}><ChevronDown size={16} /></button><button type="button" className="focus-ring grid size-9 place-items-center rounded-full hover:bg-white" onClick={onEdit} aria-label={`Edit ${item.itemName}`}><Edit3 size={15} /></button><button type="button" className="focus-ring grid size-9 place-items-center rounded-full hover:bg-white" onClick={onDuplicate} aria-label={`Duplicate ${item.itemName}`}><Copy size={15} /></button><button type="button" className="focus-ring grid size-9 place-items-center rounded-full text-[#8b3029] hover:bg-[#fff1ef]" onClick={onDelete} aria-label={`Delete ${item.itemName}`}><Trash2 size={15} /></button></div></div>
    <div className="mt-3 flex flex-wrap gap-2 text-[11px]"><Status icon={cost.amountPence == null ? <AlertCircle size={13} /> : <CheckCircle2 size={13} />} text={cost.amountPence == null ? "Missing price" : item.costStatus.replaceAll("_", " ")} warning={cost.amountPence == null} />{item.source === "website" ? <Status text="EverAft listing" /> : null}{item.dueDate ? <Status text={`Due ${new Date(`${item.dueDate}T00:00:00`).toLocaleDateString("en-GB", { day: "numeric", month: "short", year: "numeric" })}`} /> : null}{item.importedPricePence != null && cost.amountPence != null && item.importedPricePence !== cost.amountPence ? <Status text={`${formatMoney(cost.amountPence - item.importedPricePence, currency)} vs listed`} /> : null}</div></article>;
}
function SmallMetric({ label, value, warning = false }: { label: string; value: string; warning?: boolean }) { return <p><span className="block text-[11px] uppercase tracking-[0.08em] text-[#8a806f]">{label}</span><span className={`mt-1 block text-sm font-semibold ${warning ? "text-[#a44831]" : ""}`}>{value}</span></p>; }
function Status({ text, icon, warning = false }: { text: string; icon?: React.ReactNode; warning?: boolean }) { return <span className={`inline-flex items-center gap-1 rounded-full px-2.5 py-1 font-medium capitalize ${warning ? "bg-[#fff1ef] text-[#8b3029]" : "bg-[#f4efe7] text-[#625f57]"}`}>{icon}{text}</span>; }
