"use client";
import Image from "next/image";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { ExternalLink, Globe2, Search } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input, Select, Textarea } from "@/components/ui/field";
import { getPaymentStatus, parseMoneyToPence } from "@/lib/budget/calculations";
import { formatPlannerListingPrice, hasUnresolvedTax, plannerListingCanUseAsTotal, plannerListingDescription, plannerListingNeedsInput } from "@/lib/budget/listing-pricing";
import type { BudgetCategory, BudgetItem, BudgetPlan, CostStatus, PlannerListing } from "@/lib/budget/types";
import { Modal } from "./modal";

type Props = { open: boolean; plan: BudgetPlan; listings: PlannerListing[]; initialCategoryId?: string; item?: BudgetItem | null; onClose: () => void; onSave: (item: BudgetItem) => void };
type FormState = ReturnType<typeof emptyForm>;
const LISTING_RESULTS_PAGE_SIZE = 24;
function emptyForm(categoryId = "venue") { return { categoryId, itemName: "", supplierName: "", estimatedCost: "", confirmedCost: "", depositPaid: "", totalPaid: "", costStatus: "estimated" as CostStatus, bookingStatus: "researching" as BudgetItem["bookingStatus"], pricingBasis: "total" as "total" | "per_person", costPerPerson: "", guestCount: "", dueDate: "", websiteUrl: "", description: "", notes: "" }; }
function itemToForm(item: BudgetItem): FormState {
  const pounds = (value: number | null | undefined) => value == null ? "" : String(value / 100);
  return { categoryId: item.categoryId, itemName: item.itemName, supplierName: item.supplierName ?? "", estimatedCost: pounds(item.estimatedCostPence), confirmedCost: pounds(item.confirmedCostPence), depositPaid: pounds(item.depositPaidPence || null), totalPaid: pounds(item.totalPaidPence || null), costStatus: item.costStatus, bookingStatus: item.bookingStatus, pricingBasis: item.costPerPersonPence != null ? "per_person" : "total", costPerPerson: pounds(item.costPerPersonPence), guestCount: item.guestCount == null ? "" : String(item.guestCount), dueDate: item.dueDate ?? "", websiteUrl: item.websiteUrl ?? "", description: item.description ?? "", notes: item.notes ?? "" };
}

export function ExpenseDialog({ open, plan, listings, initialCategoryId, item, onClose, onSave }: Props) {
  const initialListing = item?.listingId ? listings.find((listing) => listing.id === item.listingId) ?? null : null;
  const [mode, setMode] = useState<"website" | "manual">(item?.source === "website" ? "website" : "manual");
  const [form, setForm] = useState<FormState>(() => item ? itemToForm(item) : emptyForm(initialCategoryId));
  const [selectedListing, setSelectedListing] = useState<PlannerListing | null>(initialListing);
  const [search, setSearch] = useState(""); const [debouncedSearch, setDebouncedSearch] = useState(""); const [error, setError] = useState("");
  const [visibleResultCount, setVisibleResultCount] = useState(LISTING_RESULTS_PAGE_SIZE);
  useEffect(() => { const timer = window.setTimeout(() => setDebouncedSearch(search.trim().toLowerCase()), 250); return () => window.clearTimeout(timer); }, [search]);
  const results = useMemo(() => listings.filter((listing) => listing.categoryId === form.categoryId && (!debouncedSearch || `${listing.name} ${listing.type} ${listing.location}`.toLowerCase().includes(debouncedSearch))), [debouncedSearch, form.categoryId, listings]);
  const visibleResults = results.slice(0, visibleResultCount);
  const set = <K extends keyof FormState>(key: K, value: FormState[K]) => setForm((current) => ({ ...current, [key]: value }));
  function chooseListing(listing: PlannerListing) {
    const isPerPerson = listing.pricingUnit === "per_person" || listing.pricingStatus === "per_person";
    const canUsePerPerson = isPerPerson && !hasUnresolvedTax(listing.taxLabel);
    const canUseAsTotal = plannerListingCanUseAsTotal(listing);
    setSelectedListing(listing);
    setForm((current) => ({
      ...current,
      categoryId: listing.categoryId,
      itemName: listing.name,
      supplierName: listing.name,
      pricingBasis: isPerPerson ? "per_person" : "total",
      estimatedCost: canUseAsTotal ? String(listing.priceFromPence! / 100) : "",
      costPerPerson: canUsePerPerson && listing.priceFromPence != null ? String(listing.priceFromPence / 100) : "",
      guestCount: canUsePerPerson && plan.guestCount ? String(plan.guestCount) : "",
      description: plannerListingDescription(listing) ?? current.description,
      websiteUrl: ""
    }));
  }
  function submit(event: React.FormEvent) {
    event.preventDefault(); if (!form.itemName.trim()) { setError("Enter a name for this expense."); return; }
    const estimatedCostPence = form.pricingBasis === "total" ? parseMoneyToPence(form.estimatedCost) : null;
    const confirmedCostPence = parseMoneyToPence(form.confirmedCost); const costPerPersonPence = form.pricingBasis === "per_person" ? parseMoneyToPence(form.costPerPerson) : null;
    const guestCount = form.guestCount ? Number(form.guestCount) : plan.guestCount; const depositPaidPence = parseMoneyToPence(form.depositPaid) ?? 0;
    const totalPaidPence = Math.max(parseMoneyToPence(form.totalPaid) ?? 0, depositPaidPence);
    if (form.pricingBasis === "per_person" && costPerPersonPence != null && !guestCount) { setError("Add a guest count to calculate this per-person cost."); return; }
    const now = new Date().toISOString(); const planningCost = confirmedCostPence ?? estimatedCostPence ?? (costPerPersonPence != null && guestCount ? costPerPersonPence * guestCount : null);
    onSave({ id: item?.id ?? crypto.randomUUID(), categoryId: form.categoryId, listingId: selectedListing?.id ?? item?.listingId ?? null, listingType: selectedListing?.type ?? item?.listingType ?? null, listingUrl: selectedListing?.listingUrl ?? item?.listingUrl ?? null, imageUrl: selectedListing?.imageUrl ?? item?.imageUrl ?? null, source: selectedListing ? "website" : item?.source ?? "manual", itemName: form.itemName.trim(), supplierName: form.supplierName.trim() || null, supplierType: selectedListing?.type ?? item?.supplierType ?? null, description: form.description.trim() || null, estimatedCostPence, confirmedCostPence, importedPricePence: selectedListing?.priceFromPence ?? item?.importedPricePence ?? null, importedPriceToPence: selectedListing?.priceToPence ?? item?.importedPriceToPence ?? null, importedPriceType: selectedListing?.pricingStatus ?? item?.importedPriceType ?? null, costPerPersonPence, guestCount: guestCount || null, depositPaidPence, totalPaidPence, costStatus: totalPaidPence > 0 && planningCost != null && totalPaidPence >= planningCost ? "paid" : form.costStatus, paymentStatus: getPaymentStatus(planningCost, totalPaidPence), bookingStatus: form.bookingStatus, dueDate: form.dueDate || null, websiteUrl: form.websiteUrl.trim() || null, notes: form.notes.trim() || null, createdAt: item?.createdAt ?? now, updatedAt: now, sortOrder: item?.sortOrder ?? plan.items.length });
  }
  return <Modal open={open} title={item ? "Edit expense" : "Add an expense"} description="Start with the essentials. Payment details and notes are optional." onClose={onClose}><form onSubmit={submit} className="p-5 sm:p-7">
    {!item ? <div className="mb-6 grid grid-cols-2 rounded-full bg-[#eee8dd] p-1" aria-label="Expense source"><button type="button" aria-pressed={mode === "website"} onClick={() => setMode("website")} className={`focus-ring min-h-11 rounded-full px-4 text-sm font-semibold transition ${mode === "website" ? "bg-white text-[var(--brand)] shadow-sm" : "text-[#625f57]"}`}>Select from EverAft</button><button type="button" aria-pressed={mode === "manual"} onClick={() => { setMode("manual"); setSelectedListing(null); }} className={`focus-ring min-h-11 rounded-full px-4 text-sm font-semibold transition ${mode === "manual" ? "bg-white text-[var(--brand)] shadow-sm" : "text-[#625f57]"}`}>Add manually</button></div> : null}
    {mode === "website" && !selectedListing ? <WebsiteSearch categories={plan.categories} categoryId={form.categoryId} setCategory={(value) => { set("categoryId", value); setVisibleResultCount(LISTING_RESULTS_PAGE_SIZE); }} search={search} setSearch={(value) => { setSearch(value); setVisibleResultCount(LISTING_RESULTS_PAGE_SIZE); }} results={visibleResults} totalResults={results.length} onShowMore={() => setVisibleResultCount((count) => count + LISTING_RESULTS_PAGE_SIZE)} onSelect={chooseListing} onManual={() => { setMode("manual"); setSelectedListing(null); }} /> : <div className="grid gap-5">
      {selectedListing ? <ImportedListing listing={selectedListing} onChange={() => setSelectedListing(null)} /> : null}
      <div className="grid gap-5 sm:grid-cols-2"><Label text="Item name"><Input value={form.itemName} onChange={(e) => set("itemName", e.target.value)} maxLength={160} required /></Label><Label text="Category"><Select value={form.categoryId} onChange={(e) => set("categoryId", e.target.value)}>{plan.categories.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</Select></Label><Label text="Supplier name (optional)"><Input value={form.supplierName} onChange={(e) => set("supplierName", e.target.value)} maxLength={160} /></Label><Label text="Cost status"><Select value={form.costStatus} onChange={(e) => set("costStatus", e.target.value as CostStatus)}><option value="estimated">Estimated</option><option value="quoted">Quoted</option><option value="booked">Booked</option><option value="deposit_paid">Deposit paid</option><option value="partially_paid">Partially paid</option><option value="paid">Paid in full</option><option value="cancelled">Cancelled</option></Select></Label></div>
      {selectedListing && plannerListingNeedsInput(selectedListing, plan.guestCount) ? <p className="rounded-2xl bg-[#fff4ed] px-4 py-3 text-sm leading-6 text-[#7c3f22]" role="status">{selectedListing.pricingStatus === "quote_required" ? "This business asks couples to request current pricing." : selectedListing.pricingUnit === "per_person" ? "Add your guest count so EverAft can calculate this per-person price safely." : hasUnresolvedTax(selectedListing.taxLabel) ? `The published base price has this tax qualifier: ${selectedListing.taxLabel}. Add your expected total or confirmed quote below.` : selectedListing.pricingUnit === "per_night" || selectedListing.pricingUnit === "per_room" ? "This is not a complete booking total. Add your expected total or confirmed quote below." : "This listing does not currently display a price EverAft can safely use as a total. Add your estimate or confirmed quote below."}</p> : null}
      {selectedListing?.priceFromPence != null ? <p className="rounded-2xl bg-[#eef4ea] px-4 py-3 text-sm text-[#35513a]">EverAft lists {selectedListing.pricingLabel ? `${selectedListing.pricingLabel.toLowerCase()} at ` : "this option at "}<strong>{formatPlannerListingPrice(selectedListing)}</strong>. {selectedListing.pricingKind === "minimum_spend" ? "This is a minimum spend, not a complete quote." : "It is a planning estimate and can be changed."}</p> : null}
      <fieldset className="grid gap-4 rounded-2xl border border-[var(--line)] p-4"><legend className="px-2 text-sm font-semibold">Planning cost</legend><div className="grid gap-5 sm:grid-cols-2"><Label text="Pricing basis"><Select value={form.pricingBasis} onChange={(e) => set("pricingBasis", e.target.value as "total" | "per_person")}><option value="total">Total cost</option><option value="per_person">Price per person</option></Select></Label>{form.pricingBasis === "total" ? <Label text="Estimated cost (£)"><Input inputMode="decimal" value={form.estimatedCost} onChange={(e) => set("estimatedCost", e.target.value)} placeholder="0.00" /></Label> : <><Label text="Price per person (£)"><Input inputMode="decimal" value={form.costPerPerson} onChange={(e) => set("costPerPerson", e.target.value)} placeholder="0.00" /></Label><Label text="Guest count"><Input inputMode="numeric" type="number" min="1" value={form.guestCount} onChange={(e) => set("guestCount", e.target.value)} placeholder={plan.guestCount ? String(plan.guestCount) : "e.g. 80"} /></Label></>}<Label text="Confirmed cost (£)"><Input inputMode="decimal" value={form.confirmedCost} onChange={(e) => set("confirmedCost", e.target.value)} placeholder="Leave blank until confirmed" /></Label></div><p className="text-xs leading-5 text-[var(--muted)]">A confirmed cost replaces the estimate in your totals. Imported “from” prices remain estimates.</p></fieldset>
      <details className="rounded-2xl border border-[var(--line)] bg-white p-4"><summary className="focus-ring cursor-pointer rounded-lg text-sm font-semibold">Payment details, dates and notes</summary><div className="mt-5 grid gap-5 sm:grid-cols-2"><Label text="Deposit paid (£)"><Input inputMode="decimal" value={form.depositPaid} onChange={(e) => set("depositPaid", e.target.value)} placeholder="0.00" /></Label><Label text="Total paid so far (£)"><Input inputMode="decimal" value={form.totalPaid} onChange={(e) => set("totalPaid", e.target.value)} placeholder="0.00" /></Label><Label text="Booking status"><Select value={form.bookingStatus} onChange={(e) => set("bookingStatus", e.target.value as BudgetItem["bookingStatus"])}><option value="researching">Researching</option><option value="shortlisted">Shortlisted</option><option value="quoted">Quote received</option><option value="booked">Booked</option><option value="cancelled">Cancelled</option></Select></Label><Label text="Next payment due"><Input type="date" value={form.dueDate} onChange={(e) => set("dueDate", e.target.value)} /></Label><Label text="Website or contact link"><Input type="url" value={form.websiteUrl} onChange={(e) => set("websiteUrl", e.target.value)} placeholder="https://" /></Label><Label text="Short description"><Input value={form.description} onChange={(e) => set("description", e.target.value)} maxLength={2000} /></Label><div className="sm:col-span-2"><Label text="Notes"><Textarea value={form.notes} onChange={(e) => set("notes", e.target.value)} maxLength={4000} /></Label></div></div></details>
    </div>}
    {error ? <p className="mt-5 rounded-2xl bg-[#fff1ef] px-4 py-3 text-sm font-medium text-[#8b3029]" role="alert">{error}</p> : null}
    {(mode === "manual" || selectedListing) ? <div className="mt-7 flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><Button type="button" variant="ghost" onClick={onClose}>Cancel</Button><Button type="submit">{item ? "Save changes" : "Add to budget"}</Button></div> : null}
  </form></Modal>;
}

function Label({ text, children }: { text: string; children: React.ReactNode }) { return <label className="grid gap-2 text-sm font-medium text-[#4a443c]"><span>{text}</span>{children}</label>; }
function WebsiteSearch({ categories, categoryId, setCategory, search, setSearch, results, totalResults, onShowMore, onSelect, onManual }: { categories: BudgetCategory[]; categoryId: string; setCategory: (v: string) => void; search: string; setSearch: (v: string) => void; results: PlannerListing[]; totalResults: number; onShowMore: () => void; onSelect: (l: PlannerListing) => void; onManual: () => void }) {
  return <div className="grid gap-5"><div className="grid gap-5 sm:grid-cols-2"><Label text="Supplier category"><Select value={categoryId} onChange={(e) => setCategory(e.target.value)}>{categories.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</Select></Label><Label text="Search EverAft"><span className="relative"><Search className="pointer-events-none absolute left-4 top-1/2 -translate-y-1/2 text-[#8a806f]" size={18} /><Input className="pl-11" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Business or location" /></span></Label></div>
    <div><p className="mb-2 text-xs text-[var(--muted)]" aria-live="polite">Showing {results.length} of {totalResults} matching {totalResults === 1 ? "listing" : "listings"}</p><div className="grid max-h-[46vh] gap-3 overflow-y-auto pr-1">{results.length ? <>{results.map((l) => <button key={l.id} type="button" onClick={() => onSelect(l)} className="focus-ring grid grid-cols-[64px_1fr_auto] items-center gap-4 rounded-2xl border border-[var(--line)] bg-white p-3 text-left transition hover:border-[#b99669] hover:bg-[#fffdf9]"><Image src={l.imageUrl} alt="" width={64} height={64} className="size-16 rounded-xl object-cover" /><span><strong className="block text-sm">{l.name}</strong><span className="mt-1 block text-xs text-[var(--muted)]">{l.type} · {l.location}</span></span><span className="text-right text-xs font-semibold text-[#6e4c32]"><span className="block text-[10px] font-medium uppercase tracking-wide text-[#8a806f]">{l.pricingLabel ?? "Pricing"}</span>{formatPlannerListingPrice(l)}</span></button>)}{results.length < totalResults ? <button type="button" onClick={onShowMore} className="focus-ring min-h-11 rounded-2xl border border-dashed border-[#b99669] bg-[#fffaf3] px-4 text-sm font-semibold text-[#704b31] transition hover:bg-white">Show {Math.min(LISTING_RESULTS_PAGE_SIZE, totalResults - results.length)} more listings</button> : null}</> : <div className="rounded-2xl border border-dashed border-[var(--line)] bg-white p-6 text-center"><Globe2 className="mx-auto text-[#9d7b45]" size={26} /><h3 className="mt-3 font-display text-2xl font-semibold">This category is still growing</h3><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-[var(--muted)]">No public EverAft listings match yet. You can still add the supplier and cost manually.</p></div>}</div></div>
    <Button type="button" variant="secondary" onClick={onManual}>Add manually instead</Button></div>;
}
function ImportedListing({ listing, onChange }: { listing: PlannerListing; onChange: () => void }) { return <div className="flex items-center gap-4 rounded-2xl border border-[#d7e3d2] bg-[#f4f8f1] p-3"><Image src={listing.imageUrl} alt="" width={56} height={56} className="size-14 rounded-xl object-cover" /><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{listing.name}</p><p className="mt-1 text-xs text-[#5f6d5b]">Imported from EverAft · {listing.location}</p></div><Link className="focus-ring grid size-10 place-items-center rounded-full" href={listing.listingUrl} target="_blank" aria-label={`Open ${listing.name} listing`}><ExternalLink size={16} /></Link><button type="button" className="focus-ring rounded-full px-3 py-2 text-xs font-semibold text-[#704b31] hover:bg-white" onClick={onChange}>Change</button></div>; }
