import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { approveSupplierClaim, rejectSupplierClaim } from "@/app/actions/claims";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/field";
import { requireAdmin } from "@/lib/auth";
import { createAdminClient } from "@/lib/supabase/admin";

export const metadata: Metadata = { title: "Review photographer claim" };
export default async function SupplierClaimReviewPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ message?: string }> }) {
  await requireAdmin(); const [{ id }, { message }] = await Promise.all([params, searchParams]); const supabase = createAdminClient();
  const { data: claim } = await supabase!.from("supplier_claims").select("*").eq("id", id).single(); if (!claim) notFound();
  const [{ data: supplier }, { data: audit }] = await Promise.all([supabase!.from("supplier_listings").select("*").eq("id", claim.supplier_id).single(), supabase!.from("supplier_claim_audit_log").select("*").eq("claim_id", claim.id).order("created_at", { ascending: false })]);
  const info = [["Claimant", claim.claimant_name], ["Role", claim.claimant_role], ["Account email", claim.claimant_email], ["Business email", claim.business_email], ["Business phone", claim.business_phone], ["Evidence URL", claim.evidence_url || "Not provided"]];
  return <div className="mx-auto max-w-5xl px-4 py-10 sm:px-6 lg:px-8"><Link className="text-sm font-semibold text-[#5c6b52]" href="/admin/supplier-claims">Back to photographer claims</Link><div className="mt-6 grid gap-5 lg:grid-cols-[1fr_360px]"><section className="rounded-3xl border border-[var(--line)] bg-white p-6"><p className="text-sm font-semibold uppercase tracking-[0.22em] text-[#9d7b45]">Claim request</p><h1 className="mt-3 font-display text-5xl font-semibold">{supplier?.name ?? "Photographer claim"}</h1><p className="mt-3 text-sm text-[var(--muted)]">Status: {claim.status}</p>{message ? <p className="mt-5 rounded-2xl bg-[#f4efe7] px-4 py-3 text-sm">{message}</p> : null}<dl className="mt-8 grid gap-5 sm:grid-cols-2">{info.map(([label, value]) => <div key={label}><dt className="text-xs font-semibold uppercase tracking-[0.18em] text-[#8a806f]">{label}</dt><dd className="mt-1 break-words text-sm text-[#4a443c]">{value}</dd></div>)}</dl><div className="mt-8 rounded-2xl bg-[#fbf8f3] p-5"><p className="text-sm font-semibold">Message</p><p className="mt-2 text-sm leading-6 text-[var(--muted)]">{claim.message}</p></div></section><aside className="grid gap-5 self-start"><form action={approveSupplierClaim} className="rounded-3xl border border-[var(--line)] bg-white p-5"><input name="claimId" type="hidden" value={claim.id} /><h2 className="font-display text-3xl font-semibold">Approve</h2><p className="mt-2 text-sm leading-6 text-[var(--muted)]">Grant dashboard access. The profile stays draft until it is reviewed for publication.</p><Textarea className="mt-4" defaultValue={claim.admin_notes ?? ""} name="adminNotes" placeholder="Admin notes" /><Button className="mt-4 w-full" disabled={claim.status === "approved"}>Approve claim</Button></form><form action={rejectSupplierClaim} className="rounded-3xl border border-[var(--line)] bg-white p-5"><input name="claimId" type="hidden" value={claim.id} /><h2 className="font-display text-3xl font-semibold">Reject</h2><Textarea className="mt-4" defaultValue={claim.admin_notes ?? ""} name="adminNotes" required placeholder="Reason or internal notes" /><Button className="mt-4 w-full" disabled={claim.status === "rejected"} variant="secondary">Reject claim</Button></form></aside></div><section className="mt-8 rounded-3xl border border-[var(--line)] bg-white p-6"><h2 className="font-display text-3xl font-semibold">Audit log</h2><div className="mt-5 grid gap-3">{(audit ?? []).map((entry) => <div className="rounded-2xl bg-[#fbf8f3] px-4 py-3 text-sm" key={entry.id}><p className="font-semibold">{entry.action}</p><p className="mt-1 text-[var(--muted)]">{entry.notes || "No notes"} — {new Date(entry.created_at).toLocaleString("en-GB")}</p></div>)}{(audit ?? []).length === 0 ? <p className="text-sm text-[var(--muted)]">No audit events yet.</p> : null}</div></section></div>;
}
