-- First researched photographer cohort. These records are intentionally
-- unclaimed drafts: an EverAft admin must verify them before publication.
-- No portfolio imagery is included without explicit display permission.

with photographer_seed (
  slug,
  name,
  base_town,
  region,
  service_areas,
  travels_nationwide,
  summary,
  description,
  services,
  official_website_url,
  source_url
) as (
  values
    (
      'loraine-ross-photography',
      'Loraine Ross Photography',
      'Edinburgh',
      'City of Edinburgh',
      array['City of Edinburgh', 'Scottish Borders'],
      true,
      'Edinburgh wedding photographer working with both digital and analogue film.',
      'Loraine Ross photographs weddings and elopements from Edinburgh, combining digital coverage with 35mm and medium-format film across Scotland.',
      array['Wedding photography', 'Elopement photography', 'Analogue film photography'],
      'https://lorainerossweddings.co.uk/',
      'https://lorainerossweddings.co.uk/'
    ),
    (
      'claire-fleck-photography',
      'Claire Fleck Photography',
      'Edinburgh',
      'City of Edinburgh',
      array['City of Edinburgh'],
      true,
      'Edinburgh-based wedding photographer creating natural and contemporary imagery.',
      'Claire Fleck Photography covers weddings from Edinburgh with an approach centred on candid, down-to-earth and contemporary photographs.',
      array['Wedding photography'],
      'https://clairefleckphotography.com/',
      'https://clairefleckphotography.com/'
    ),
    (
      'hamish-robb-photography',
      'Hamish Robb Photography',
      'Edinburgh',
      'City of Edinburgh',
      array['City of Edinburgh', 'Fife', 'Perth and Kinross'],
      true,
      'Documentary wedding photographer covering Edinburgh, Fife and celebrations across Scotland.',
      'Hamish Robb offers documentary wedding photography from an Edinburgh base, with experience across Fife, St Andrews, Perthshire and the rest of Scotland.',
      array['Wedding photography', 'Pre-wedding shoots'],
      'https://www.hamishrobb.co.uk/',
      'https://www.hamishrobb.co.uk/'
    ),
    (
      'natalia-swiader-photography',
      'Natalia Swiader Photography',
      'Edinburgh',
      'City of Edinburgh',
      array['City of Edinburgh', 'Highland'],
      true,
      'Edinburgh-based elopement photographer creating moody, story-led images around Scotland.',
      'Natalia Swiader focuses on Scottish elopements and intimate weddings, blending landscape, weather and candid moments into cinematic visual stories.',
      array['Elopement photography', 'Intimate wedding photography'],
      'https://nataliaswiader.com/',
      'https://nataliaswiader.com/'
    ),
    (
      'a-fotografy',
      'A-Fotografy',
      'Edinburgh',
      'City of Edinburgh',
      array['City of Edinburgh'],
      true,
      'Creative Edinburgh wedding photographer covering celebrations in Scotland and further afield.',
      'A-Fotografy photographs weddings from Edinburgh with a creative approach and availability for celebrations across Scotland, the UK and internationally.',
      array['Wedding photography'],
      'https://weddings.a-fotografy.co.uk/',
      'https://weddings.a-fotografy.co.uk/edinburgh-scottish-photographer/'
    ),
    (
      'soul-photography-edinburgh',
      'Soul Photography',
      'Edinburgh',
      'City of Edinburgh',
      array['City of Edinburgh'],
      true,
      'Edinburgh wedding photography and videography team available throughout Scotland.',
      'Soul Photography provides wedding photography and video coverage from Edinburgh and states that it travels throughout Scotland for celebrations.',
      array['Wedding photography', 'Wedding videography'],
      'https://www.krissoulphotography.co.uk/',
      'https://www.krissoulphotography.co.uk/'
    ),
    (
      'anna-urban-photography',
      'Anna Urban Photography',
      'Edinburgh',
      'City of Edinburgh',
      array['City of Edinburgh', 'Scottish Borders'],
      true,
      'Edinburgh wedding photographer working across analogue and digital formats.',
      'Anna Urban photographs weddings from Edinburgh using both analogue and digital photography, with work across Scotland and worldwide destinations.',
      array['Wedding photography', 'Analogue film photography'],
      'https://www.annaurban.com/',
      'https://www.annaurban.com/farm-wedding-scottish-borders/'
    ),
    (
      'good-luck-wolf-photography',
      'Good Luck Wolf Photography',
      'Glasgow',
      'Glasgow City',
      array['Glasgow City'],
      true,
      'Glasgow wedding photographer focused on natural moments and relaxed celebrations.',
      'Good Luck Wolf is based in Glasgow and photographs weddings in the city and throughout Scotland with a relaxed, natural approach.',
      array['Wedding photography'],
      'https://goodluckwolf.co.uk/',
      'https://goodluckwolf.co.uk/'
    ),
    (
      'joy-story',
      'Joy Story',
      'Glasgow',
      'Glasgow City',
      array['Glasgow City'],
      true,
      'Colourful Glasgow wedding photographer covering joyful celebrations across Scotland.',
      'Joy Story photographs weddings from Glasgow with a colourful, alternative style focused on genuine moments and energetic celebrations throughout Scotland.',
      array['Wedding photography'],
      'https://joystory.co.uk/',
      'https://joystory.co.uk/'
    ),
    (
      'john-johnston-photography',
      'John Johnston Photography',
      'Glasgow',
      'Glasgow City',
      array['Glasgow City'],
      true,
      'Experienced Glasgow wedding photographer covering celebrations throughout Scotland.',
      'John Johnston Photography works from Glasgow and takes a natural, unobtrusive approach that allows a wedding day to unfold without unnecessary interruption.',
      array['Wedding photography', 'Elopement photography'],
      'https://johnjohnstonphotography.co.uk/',
      'https://johnjohnstonphotography.co.uk/'
    ),
    (
      'francis-j-smith-photography',
      'Francis J Smith Photography',
      'Glasgow',
      'Glasgow City',
      array['Glasgow City'],
      true,
      'Glasgow documentary wedding photographer working across Scotland and the UK.',
      'Francis J Smith combines documentary coverage with cinematic portraits and compositions while photographing weddings throughout Scotland and the wider UK.',
      array['Wedding photography', 'Elopement photography'],
      'https://francisjsmith.co.uk/',
      'https://francisjsmith.co.uk/'
    ),
    (
      'richard-campbell-photography-glasgow',
      'Richard Campbell Photography Glasgow',
      'Glasgow',
      'Glasgow City',
      array['Glasgow City'],
      true,
      'Natural Glasgow wedding photographer available for celebrations anywhere in Scotland.',
      'Richard Campbell Photography is based in Glasgow and uses a quiet, natural approach designed to let couples enjoy their day while genuine moments are captured.',
      array['Wedding photography'],
      'https://www.richardcampbellphotography.co.uk/',
      'https://www.richardcampbellphotography.co.uk/'
    ),
    (
      'scott-arlow-photography',
      'Scott Arlow Photography',
      'Aberdeen',
      'Aberdeen City',
      array['Aberdeen City', 'Aberdeenshire'],
      false,
      'Aberdeen wedding photographer with a candid, relaxed documentary approach.',
      'Scott Arlow is based in Aberdeen and focuses on natural interactions, in-between moments and documentary storytelling throughout a wedding day.',
      array['Wedding photography'],
      'https://scottarlowphotography.com/',
      'https://scottarlowphotography.com/meet-scott'
    ),
    (
      'fitlike-photography',
      'Fitlike Photography',
      'Aberdeen',
      'Aberdeen City',
      array['Aberdeen City', 'Aberdeenshire'],
      false,
      'Aberdeen wedding photographer specialising in modern documentary coverage.',
      'Fitlike Photography, led by Mike Custer, photographs weddings in Aberdeen and the surrounding area with a modern documentary style.',
      array['Wedding photography'],
      'https://www.fitlikephotography.co.uk/',
      'https://www.fitlikephotography.co.uk/blog/modern-documentary-wedding-photography-for-elegant-aberdeen-weddings/77/'
    ),
    (
      'jamie-emerson-photography',
      'Jamie Emerson Photography',
      'Aberdeen',
      'Aberdeen City',
      array['Aberdeen City', 'Aberdeenshire'],
      false,
      'Aberdeen documentary wedding photographer focused on natural, story-led images.',
      'Jamie Emerson photographs weddings from Aberdeen with an experienced documentary approach centred on emotion, fleeting moments and the complete story of the day.',
      array['Wedding photography'],
      'https://www.jamieemersonphotography.com/',
      'https://www.jamieemersonphotography.com/'
    ),
    (
      'chris-henderson-photography',
      'Chris Henderson Photography',
      'Aberdeen',
      'Aberdeen City',
      array['Aberdeen City', 'Aberdeenshire'],
      true,
      'Aberdeen documentary wedding photographer serving celebrations across Scotland and beyond.',
      'Chris Henderson creates unposed wedding photographs from an Aberdeen base, blending into the celebration to document genuine moments as they happen.',
      array['Wedding photography'],
      'https://www.chrishenderson.co/',
      'https://www.chrishenderson.co/'
    ),
    (
      'calum-riddell-photography',
      'Calum Riddell Photography',
      'Stonehaven',
      'Aberdeenshire',
      array['Aberdeenshire', 'Aberdeen City'],
      true,
      'Stonehaven wedding photographer and filmmaker creating natural, story-driven coverage.',
      'Calum Riddell works from Stonehaven near Aberdeen, providing wedding photography and highlight films for celebrations throughout Scotland.',
      array['Wedding photography', 'Wedding videography'],
      'https://www.calumriddell.com/',
      'https://www.calumriddell.com/'
    ),
    (
      'andy-allan-photography',
      'Andy Allan Photography',
      'Inverness',
      'Highland',
      array['Highland', 'Aberdeen City', 'Aberdeenshire'],
      true,
      'Inverness wedding photographer covering weddings and elopements across Scotland.',
      'Andy Allan Photography is based in the Highlands and creates natural, timeless coverage for weddings and elopements around Inverness and throughout Scotland.',
      array['Wedding photography', 'Elopement photography'],
      'https://www.andyallan.co.uk/',
      'https://www.andyallan.co.uk/inverness-wedding-photographer-gallery/'
    ),
    (
      'allan-law-photography',
      'Allan Law Photography',
      'Inverness',
      'Highland',
      array['Highland'],
      true,
      'Inverness wedding and elopement photographer with a relaxed storytelling approach.',
      'Allan Law Photography has photographed weddings across the Highlands for many years, focusing on natural, emotive images and an unforced experience.',
      array['Wedding photography', 'Elopement photography'],
      'https://www.allanlawphotography.co.uk/',
      'https://www.allanlawphotography.co.uk/'
    ),
    (
      'steven-gallagher-photography',
      'Steven Gallagher Photography',
      'Inverness',
      'Highland',
      array['Highland'],
      false,
      'Inverness wedding photographer creating adventurous and cinematic Highland images.',
      'Steven Gallagher is based in Inverness and photographs Highland weddings and elopements for couples drawn to outdoor settings, landscapes and cinematic imagery.',
      array['Wedding photography', 'Elopement photography'],
      'https://stevengallagher.co.uk/',
      'https://stevengallagher.co.uk/'
    ),
    (
      'roddy-mackay-photography',
      'Roddy Mackay Photography',
      'Inverness',
      'Highland',
      array['Highland'],
      true,
      'Inverness photographer covering weddings and elopements throughout the Highlands.',
      'Roddy Mackay is an Inverness-based photographer whose wedding and elopement work uses a natural editorial approach to tell stories of people and places.',
      array['Wedding photography', 'Elopement photography', 'Pre-wedding shoots'],
      'https://roddymackay.com/',
      'https://roddymackay.com/'
    ),
    (
      'simon-murray-wedding-photographer',
      'Simon Murray Wedding Photographer',
      'Perth',
      'Perth and Kinross',
      array['Perth and Kinross', 'Dundee City', 'Fife'],
      false,
      'Perth wedding photographer working across Perthshire, Dundee and Fife.',
      'Simon Murray is based in Perth and photographs weddings across Perthshire and neighbouring areas including Dundee and Fife.',
      array['Wedding photography'],
      'https://simonmurrayweddingphotographer.co.uk/',
      'https://simonmurrayweddingphotographer.co.uk/'
    ),
    (
      'siobhan-diamond-photography',
      'Siobhan Diamond Photography',
      'Dundee',
      'Dundee City',
      array['Dundee City', 'Angus', 'Fife'],
      true,
      'Dundee-based wedding photographer covering celebrations across Scotland and beyond.',
      'Siobhan Diamond Photography works from Dundee and brings extensive wedding experience to celebrations across Scotland, including city weddings and Highland elopements.',
      array['Wedding photography', 'Elopement photography'],
      'https://siobhandiamond.co.uk/',
      'https://siobhandiamond.co.uk/contact-1'
    ),
    (
      'zibiz-photo',
      'ZibiZ Photo',
      'Dundee',
      'Dundee City',
      array['Dundee City', 'Angus', 'Fife'],
      false,
      'Dundee-based wedding photographer serving couples across Scotland.',
      'ZibiZ Photo is a wedding photography business based in Dundee, covering weddings in the city and across surrounding Scottish regions.',
      array['Wedding photography'],
      'https://www.zibizphoto.com/',
      'https://www.zibizphoto.com/'
    ),
    (
      'peter-j-stevenson-photography',
      'Peter J. Stevenson Photography',
      'Dalry',
      'North Ayrshire',
      array['North Ayrshire', 'South Ayrshire', 'East Ayrshire'],
      false,
      'Dalry wedding photographer offering natural and documentary coverage in Ayrshire.',
      'Peter J. Stevenson Photography is based in Dalry, North Ayrshire, and focuses on candid wedding storytelling with minimal staging.',
      array['Wedding photography'],
      'https://peterjstevensonphotography.co.uk/',
      'https://peterjstevensonphotography.co.uk/'
    ),
    (
      'richard-campbell-photography-ayrshire',
      'Richard Campbell Photography Ayrshire',
      'Ayr',
      'South Ayrshire',
      array['South Ayrshire', 'North Ayrshire', 'East Ayrshire'],
      true,
      'Experienced Ayr wedding photographer travelling throughout Scotland.',
      'Richard Campbell Photography is based in Ayr and photographs weddings across Scotland, with long-standing experience of Ayrshire celebrations.',
      array['Wedding photography', 'Elopement photography', 'Engagement shoots'],
      'https://www.richardcampbell.co.uk/',
      'https://www.richardcampbell.co.uk/'
    ),
    (
      'derek-dunlop-photography',
      'Derek Dunlop Photography',
      'Troon',
      'South Ayrshire',
      array['South Ayrshire', 'North Ayrshire', 'East Ayrshire'],
      true,
      'Troon wedding photographer creating emotive and stylish imagery across Scotland.',
      'Derek Dunlop Photography is based in Troon, Ayrshire, with an approach described as iconic, emotive, stylish and timeless for Scottish weddings.',
      array['Wedding photography'],
      'https://www.derekdunlopphotography.com/',
      'https://www.derekdunlopphotography.com/'
    ),
    (
      'thomas-mccabe-photography',
      'Thomas McCabe Photography',
      'Ayr',
      'South Ayrshire',
      array['South Ayrshire', 'North Ayrshire', 'East Ayrshire'],
      true,
      'Ayr wedding photographer specialising in natural, relaxed storytelling.',
      'Thomas McCabe photographs weddings from Ayr with an unobtrusive documentary approach focused on genuine laughter, emotion and unposed moments.',
      array['Wedding photography', 'Elopement photography'],
      'https://thomasmccabephotography.co.uk/',
      'https://thomasmccabephotography.co.uk/'
    ),
    (
      'graeme-webb-photography',
      'Graeme Webb Photography',
      'Hawick',
      'Scottish Borders',
      array['Scottish Borders', 'City of Edinburgh', 'East Lothian', 'Midlothian'],
      false,
      'Hawick wedding photographer covering the Scottish Borders, Edinburgh and the Lothians.',
      'Graeme Webb Photography takes a relaxed and natural approach, working from Hawick across the Borders, Edinburgh and the Lothians.',
      array['Wedding photography'],
      'https://gwphotography.co.uk/',
      'https://gwphotography.co.uk/'
    ),
    (
      'parris-photography',
      'Parris Photography',
      'Hawick',
      'Scottish Borders',
      array['Scottish Borders', 'City of Edinburgh', 'Glasgow City'],
      true,
      'Hawick husband-and-wife photography team covering weddings across Scotland and beyond.',
      'John and Sandra Parris run Parris Photography from Hawick in the Scottish Borders, providing two-photographer wedding coverage across Scotland, the UK and internationally.',
      array['Wedding photography', 'Two-photographer coverage'],
      'https://www.parrisphotography.co.uk/',
      'https://www.parrisphotography.co.uk/'
    ),
    (
      'hemera-visuals',
      'Hemera Visuals',
      'Dumfries',
      'Dumfries and Galloway',
      array['Dumfries and Galloway'],
      true,
      'Dumfries wedding photographer available across Scotland and the wider UK.',
      'Hemera Visuals is led by Dumfries photographer Cameron Pagan and focuses on intimate, joyful wedding moments for celebrations around Dumfries and further afield.',
      array['Wedding photography'],
      'https://www.hemeravisuals.co.uk/',
      'https://www.hemeravisuals.co.uk/'
    )
)
insert into public.supplier_listings (
  category_slug,
  slug,
  name,
  base_town,
  region,
  country,
  service_areas,
  travels_nationwide,
  summary,
  description,
  services,
  official_website_url,
  source_url,
  pricing_unit,
  listing_status,
  claim_status,
  is_claimed,
  image_permission_status
)
select
  'photographer',
  slug,
  name,
  base_town,
  region,
  'Scotland',
  service_areas,
  travels_nationwide,
  summary,
  description,
  services,
  official_website_url,
  source_url,
  'quote',
  'draft',
  'unclaimed',
  false,
  'representative'
from photographer_seed
on conflict (slug) do nothing;

with photographer_style_seed (slug, styles, film_photography_available) as (
  values
    ('loraine-ross-photography', array['Film-inspired', 'Editorial'], true),
    ('claire-fleck-photography', array['Natural', 'Documentary'], null),
    ('hamish-robb-photography', array['Documentary'], null),
    ('natalia-swiader-photography', array['Dark and moody', 'Creative'], null),
    ('a-fotografy', array['Creative'], null),
    ('soul-photography-edinburgh', array[]::text[], null),
    ('anna-urban-photography', array['Film-inspired'], true),
    ('good-luck-wolf-photography', array['Natural'], null),
    ('joy-story', array['Creative', 'Natural'], null),
    ('john-johnston-photography', array['Natural', 'Documentary'], null),
    ('francis-j-smith-photography', array['Documentary', 'Creative'], null),
    ('richard-campbell-photography-glasgow', array['Natural', 'Documentary'], null),
    ('scott-arlow-photography', array['Documentary', 'Natural'], null),
    ('fitlike-photography', array['Documentary'], null),
    ('jamie-emerson-photography', array['Documentary'], null),
    ('chris-henderson-photography', array['Documentary'], null),
    ('calum-riddell-photography', array['Natural', 'Documentary'], null),
    ('andy-allan-photography', array['Natural'], null),
    ('allan-law-photography', array['Natural', 'Documentary'], null),
    ('steven-gallagher-photography', array['Creative'], null),
    ('roddy-mackay-photography', array['Editorial', 'Natural'], null),
    ('simon-murray-wedding-photographer', array[]::text[], null),
    ('siobhan-diamond-photography', array[]::text[], null),
    ('zibiz-photo', array[]::text[], null),
    ('peter-j-stevenson-photography', array['Natural', 'Documentary'], null),
    ('richard-campbell-photography-ayrshire', array['Natural'], null),
    ('derek-dunlop-photography', array['Editorial'], null),
    ('thomas-mccabe-photography', array['Natural', 'Documentary'], null),
    ('graeme-webb-photography', array['Natural'], null),
    ('parris-photography', array['Creative', 'Traditional'], null),
    ('hemera-visuals', array['Natural'], null)
)
insert into public.photographer_profiles (supplier_id, styles, film_photography_available)
select listings.id, styles.styles, styles.film_photography_available
from photographer_style_seed styles
join public.supplier_listings listings on listings.slug = styles.slug
on conflict (supplier_id) do nothing;

notify pgrst, 'reload schema';
