import { describe, expect, it } from "vitest";
import { calculateBudget, findDuplicateImportedListing, getItemPlanningCost, parseMoneyToPence } from "./calculations";
import { createEmptyBudgetPlan } from "./persistence";
import type { BudgetItem } from "./types";
function item(overrides: Partial<BudgetItem> = {}): BudgetItem { return { id: "item-1", categoryId: "venue", listingId: null, listingType: null, listingUrl: null, imageUrl: null, source: "manual", itemName: "Venue", supplierName: null, supplierType: null, description: null, estimatedCostPence: null, confirmedCostPence: null, importedPricePence: null, importedPriceToPence: null, importedPriceType: null, costPerPersonPence: null, guestCount: null, depositPaidPence: 0, totalPaidPence: 0, costStatus: "estimated", paymentStatus: "not_started", bookingStatus: "researching", dueDate: null, websiteUrl: null, notes: null, createdAt: "2026-01-01T00:00:00.000Z", updatedAt: "2026-01-01T00:00:00.000Z", sortOrder: 0, ...overrides }; }
describe("budget calculations", () => {
  it("handles an empty budget and visibly tracks a missing cost", () => { const plan = createEmptyBudgetPlan(); expect(calculateBudget(plan)).toMatchObject({ allocatedPence: 0, remainingPence: 0, activeItemCount: 0 }); plan.items = [item()]; expect(calculateBudget(plan).missingPriceCount).toBe(1); });
  it("uses a confirmed cost instead of an estimate", () => expect(getItemPlanningCost(item({ estimatedCostPence: 100_000, confirmedCostPence: 125_000 }))).toEqual({ amountPence: 125_000, kind: "confirmed" }));
  it("calculates per-person pricing using the item guest count", () => expect(getItemPlanningCost(item({ costPerPersonPence: 8_500, guestCount: 80 }))).toEqual({ amountPence: 680_000, kind: "per_person" }));
  it("separates deposits and outstanding payments from remaining budget", () => { const plan = createEmptyBudgetPlan(); plan.totalBudgetPence = 2_000_000; plan.items = [item({ confirmedCostPence: 600_000, depositPaidPence: 100_000, totalPaidPence: 100_000 })]; expect(calculateBudget(plan)).toMatchObject({ remainingPence: 1_400_000, totalPaidPence: 100_000, outstandingPence: 500_000 }); });
  it("reserves percentage contingency and detects over-budget plans", () => { const plan = createEmptyBudgetPlan(); plan.totalBudgetPence = 1_000_000; plan.contingencyType = "percentage"; plan.contingencyValue = 5; plan.items = [item({ estimatedCostPence: 975_000 })]; expect(calculateBudget(plan)).toMatchObject({ contingencyPence: 50_000, spendableBudgetPence: 950_000, remainingPence: -25_000, health: "over" }); });
  it("does not count cancelled items", () => { const plan = createEmptyBudgetPlan(); plan.totalBudgetPence = 1_000_000; plan.items = [item({ estimatedCostPence: 500_000, costStatus: "cancelled" })]; expect(calculateBudget(plan)).toMatchObject({ allocatedPence: 0, activeItemCount: 0 }); });
  it("parses decimal currency safely into pence", () => { expect(parseMoneyToPence("£1,234.56")).toBe(123_456); expect(parseMoneyToPence("-10")).toBeNull(); expect(parseMoneyToPence("12.345")).toBeNull(); });
  it("finds duplicate imported listings but excludes the item being edited", () => { const items = [item({ listingId: "venue-1" })]; expect(findDuplicateImportedListing(items, "venue-1")?.id).toBe("item-1"); expect(findDuplicateImportedListing(items, "venue-1", "item-1")).toBeUndefined(); });
});
